name: Build
on:
    pull_request:
        branches: [dev]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.18.1]

        steps:
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install and npm run build
              run: |
                  npm ci
                  npm run build:ci

            - name: Run Jasmine tests
              run: npm run test --no-watch --code-coverage --browsers=ChromeHeadlessCustom

            - name: Comment Test Coverage
              uses: AthleticNet/comment-test-coverage@1.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: coverage/coverage-summary.json
                  title: Karma Test Coverage

            #- name: Run Unit Tests
            # run: npm test
            # uses: colbyhill21/angular-full-ci/@v1.0
            #uses: ng test
            #with:
            #testcommand: run test:ci
